name: "Terragrunt Deployment"

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terragrunt:
    name: "Terragrunt Plan & Apply"
    runs-on: ubuntu-latest
    environment: oci-infrastructure
    if: github.actor == github.repository_owner

    defaults:
      run:
        working-directory: ./terraform

    env:
      # S3 Remote State Backend
      AWS_ACCESS_KEY_ID: ${{ secrets.OCI_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OCI_S3_SECRET_KEY }}

      # Standard OCI SDK/CLI Variables. Natively read by the Terraform OCI Provider
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

      # Mapping OCI standard variables directly to your custom TF_VARs to prevent repetition
      TF_VAR_user_ocid: ${{ secrets.OCI_CLI_USER }}
      TF_VAR_tenancy_ocid: ${{ secrets.OCI_CLI_TENANCY }}
      TF_VAR_fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
      TF_VAR_private_key:  ${{ secrets.OCI_CLI_KEY_CONTENT }}
      TF_VAR_region: ${{ secrets.OCI_CLI_REGION }}
      TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}

      # Terragrunt CLI
      TG_NON_INTERACTIVE: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v3
#
#      - name: Setup Terragrunt
#        uses: autero1/action-terragrunt@v3
#        with:
#          terragrunt-version: 1.1.2
#          token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Terragrunt Plan
#        run: terragrunt run --all plan
#
#      - name: Terragrunt Apply
#        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#        run: terragrunt run --all apply